name: appstructure
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.4

environment:
  #sdk: '>=2.17.1 <3.0.0'
  #sdk: '>=2.19.5 <3.0.0'
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  provider: ^6.0.3
  shared_preferences: ^2.0.6
  http: ^0.13.3
  #flutter_screenutil: ^5.0.0+2
  flutter_screenutil: ^5.8.4
  #gen_lang: ^0.1.3
  #intl: ^0.17.0
  intl: ^0.18.0
  carousel_slider: ^4.1.1
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.0.1
  dots_indicator: ^3.0.0
  persistent_bottom_nav_bar_v2: ^4.2.4
  flutter_multi_select_items: ^0.4.2
  google_maps_flutter: ^2.1.10
  flutter_cached_pdfview: ^0.4.1
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.5
  flutter_share: ^2.0.0
  #flutter_html: ^2.2.1
  flutter_html: ^3.0.0-alpha.6
  flutter_advanced_seekbar: ^0.0.2
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  sn_progress_dialog: ^1.1.3
  get_storage: ^2.0.3
  #fijkplayer: ^0.10.1
  #fijkplayer_new: ^0.10.2
  full_screen_image_null_safe: ^2.0.0
  youtube_player_flutter: ^8.1.0
  dialogs: ^0.0.7
  open_filex: ^4.1.1
  html: ^0.15.0
  photo_view: ^0.14.0
  webview_flutter: ^4.2.2
  #version_check: ^0.3.0
  version_check: ^0.4.0
  visibility_detector: ^0.4.0+2
  open_store: ^0.5.0
  file: ^6.1.4
  flutter_swiper_null_safety: ^1.0.2
  #wakelock: ^0.6.2
  flu_wake_lock: ^0.0.2
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.32
  just_audio_background: ^0.0.1-beta.9
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^14.1.1
  app_settings: ^4.2.0
  firebase_analytics: ^10.2.1
  #device_info_plus: ^8.2.1
  flutter_udid: ^2.0.1
  fluttertoast: ^8.2.1
  flutter_web_browser: ^0.17.1
  flutter_timezone: ^1.0.4
  image: ^4.0.16
  flutter_inappwebview: ^5.7.2+3
  liplayer: ^0.0.2
  preload_page_view: ^0.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lang/
    - assets/strings/
    - assets/strings/en.json
    - assets/strings/hi.json

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
